# Generated by Django 5.2.7 on 2025-11-12 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='strike_count',
            field=models.IntegerField(default=0, help_text='Number of missed deadlines.'),
        ),
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='The user who created and manages the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='The calculated deadline for the task.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(choices=[(0, 'Not Started'), (25, '25%'), (50, '50%'), (75, '75%'), (100, 'Done')], default=0, help_text='Task completion percentage.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('OVERDUE', 'Overdue')], default='TODO', max_length=20),
        ),
    ]
