# Generated by Django 5.2.7 on 2025-11-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employeeprofile_strike_count_project_leader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='current_workload',
        ),
    ]
